var $ = layui.$,
	jQuery = layui.jquery,
	layer = layui.layer,//弹出层
	laydate = layui.laydate,//日期和时间组件文档
	laypage = layui.laypage,//分页
	laytpl = layui.laytpl,//模板引擎
	table = layui.table,//数据表格
	form = layui.form,//表单
	upload = layui.upload,//文件上传
	element = layui.element,//常用元素操作
	carousel = layui.carousel,//轮播
	flow = layui.flow,//流加载
	util = layui.util;//工具集
	layedit = layui.layedit;//编辑器
	//code = layui.code,//代码修饰器
